
package formularios;

/**
 *
 * @author Jeffer_King11
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setLocationRelativeTo(null);//centramos formulario al entrar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuopciones = new javax.swing.JMenuBar();
        opDatos = new javax.swing.JMenu();
        subdatos = new javax.swing.JMenuItem();
        opSalir = new javax.swing.JMenu();
        subsalir = new javax.swing.JMenuItem();
        opAbout = new javax.swing.JMenu();
        subinfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        opDatos.setText("Datos");

        subdatos.setText("Registro de usuarios");
        subdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subdatosActionPerformed(evt);
            }
        });
        opDatos.add(subdatos);

        mnuopciones.add(opDatos);

        opSalir.setText("Salir");

        subsalir.setText("Salir");
        subsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsalirActionPerformed(evt);
            }
        });
        opSalir.add(subsalir);

        mnuopciones.add(opSalir);

        opAbout.setText("Acerca de...");

        subinfo.setText("Información");
        subinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subinfoActionPerformed(evt);
            }
        });
        opAbout.add(subinfo);

        mnuopciones.add(opAbout);

        setJMenuBar(mnuopciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subdatosActionPerformed
       datos frmdatos = new datos();
       frmdatos.setVisible(true);
    }//GEN-LAST:event_subdatosActionPerformed

    private void subsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsalirActionPerformed
        System.exit(0);//salir de la aplicación
    }//GEN-LAST:event_subsalirActionPerformed

    private void subinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subinfoActionPerformed
       About formulario = new About();
       formulario.setVisible(true);
    }//GEN-LAST:event_subinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnuopciones;
    private javax.swing.JMenu opAbout;
    private javax.swing.JMenu opDatos;
    private javax.swing.JMenu opSalir;
    private javax.swing.JMenuItem subdatos;
    private javax.swing.JMenuItem subinfo;
    private javax.swing.JMenuItem subsalir;
    // End of variables declaration//GEN-END:variables
}
